import 'package:test/test.dart';
import 'package:mosquito_alert/mosquito_alert.dart';

// tests for Fix
void main() {
  final instance = FixBuilder();
  // TODO add properties to the builder and call build()

  group(Fix, () {
    // String coverageUuid
    test('to test the property `coverageUuid`', () async {
      // TODO
    });

    // OffsetDateTime createdAt
    test('to test the property `createdAt`', () async {
      // TODO
    });

    // OffsetDateTime sentAt
    test('to test the property `sentAt`', () async {
      // TODO
    });

    // Date and time registered by server when it received fix upload. Automatically generated by server.
    // OffsetDateTime receivedAt
    test('to test the property `receivedAt`', () async {
      // TODO
    });

    // FixLocation point
    test('to test the property `point`', () async {
      // TODO
    });

    // Power level of phone at time fix recorded, expressed as proportion of full charge. Range: 0-1.
    // double power
    test('to test the property `power`', () async {
      // TODO
    });

  });
}
