// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'serializers.dart';

// **************************************************************************
// BuiltValueGenerator
// **************************************************************************

Serializers _$serializers = (new Serializers().toBuilder()
      ..add(AppUserTokenObtainPair.serializer)
      ..add(AppUserTokenObtainPairRequest.serializer)
      ..add(AuthChangePasswordError.serializer)
      ..add(AuthChangePasswordNonFieldErrorsErrorComponent.serializer)
      ..add(AuthChangePasswordNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(AuthChangePasswordNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(AuthChangePasswordPasswordErrorComponent.serializer)
      ..add(AuthChangePasswordPasswordErrorComponentAttrEnum.serializer)
      ..add(AuthChangePasswordPasswordErrorComponentCodeEnum.serializer)
      ..add(AuthChangePasswordValidationError.serializer)
      ..add(AuthChangePasswordValidationErrorTypeEnum.serializer)
      ..add(AuthObtainTokenDeviceIdErrorComponent.serializer)
      ..add(AuthObtainTokenDeviceIdErrorComponentAttrEnum.serializer)
      ..add(AuthObtainTokenDeviceIdErrorComponentCodeEnum.serializer)
      ..add(AuthObtainTokenError.serializer)
      ..add(AuthObtainTokenNonFieldErrorsErrorComponent.serializer)
      ..add(AuthObtainTokenNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(AuthObtainTokenNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(AuthObtainTokenPasswordErrorComponent.serializer)
      ..add(AuthObtainTokenPasswordErrorComponentAttrEnum.serializer)
      ..add(AuthObtainTokenPasswordErrorComponentCodeEnum.serializer)
      ..add(AuthObtainTokenUsernameErrorComponent.serializer)
      ..add(AuthObtainTokenUsernameErrorComponentAttrEnum.serializer)
      ..add(AuthObtainTokenUsernameErrorComponentCodeEnum.serializer)
      ..add(AuthObtainTokenValidationError.serializer)
      ..add(AuthObtainTokenValidationErrorTypeEnum.serializer)
      ..add(AuthRefreshTokenError.serializer)
      ..add(AuthRefreshTokenNonFieldErrorsErrorComponent.serializer)
      ..add(AuthRefreshTokenNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(AuthRefreshTokenNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(AuthRefreshTokenRefreshErrorComponent.serializer)
      ..add(AuthRefreshTokenRefreshErrorComponentAttrEnum.serializer)
      ..add(AuthRefreshTokenRefreshErrorComponentCodeEnum.serializer)
      ..add(AuthRefreshTokenValidationError.serializer)
      ..add(AuthRefreshTokenValidationErrorTypeEnum.serializer)
      ..add(AuthSignupGuestError.serializer)
      ..add(AuthSignupGuestNonFieldErrorsErrorComponent.serializer)
      ..add(AuthSignupGuestNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(AuthSignupGuestNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(AuthSignupGuestPasswordErrorComponent.serializer)
      ..add(AuthSignupGuestPasswordErrorComponentAttrEnum.serializer)
      ..add(AuthSignupGuestPasswordErrorComponentCodeEnum.serializer)
      ..add(AuthSignupGuestValidationError.serializer)
      ..add(AuthSignupGuestValidationErrorTypeEnum.serializer)
      ..add(AuthVerifyTokenError.serializer)
      ..add(AuthVerifyTokenNonFieldErrorsErrorComponent.serializer)
      ..add(AuthVerifyTokenNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(AuthVerifyTokenNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(AuthVerifyTokenTokenErrorComponent.serializer)
      ..add(AuthVerifyTokenTokenErrorComponentAttrEnum.serializer)
      ..add(AuthVerifyTokenTokenErrorComponentCodeEnum.serializer)
      ..add(AuthVerifyTokenValidationError.serializer)
      ..add(AuthVerifyTokenValidationErrorTypeEnum.serializer)
      ..add(Bite.serializer)
      ..add(BiteEventEnvironmentEnum.serializer)
      ..add(BiteEventMomentEnum.serializer)
      ..add(BiteRequest.serializer)
      ..add(BiteRequestEventEnvironmentEnum.serializer)
      ..add(BiteRequestEventMomentEnum.serializer)
      ..add(BitesCreateChestBiteCountErrorComponent.serializer)
      ..add(BitesCreateChestBiteCountErrorComponentAttrEnum.serializer)
      ..add(BitesCreateChestBiteCountErrorComponentCodeEnum.serializer)
      ..add(BitesCreateCreatedAtErrorComponent.serializer)
      ..add(BitesCreateCreatedAtErrorComponentAttrEnum.serializer)
      ..add(BitesCreateCreatedAtErrorComponentCodeEnum.serializer)
      ..add(BitesCreateError.serializer)
      ..add(BitesCreateEventEnvironmentErrorComponent.serializer)
      ..add(BitesCreateEventEnvironmentErrorComponentAttrEnum.serializer)
      ..add(BitesCreateEventEnvironmentErrorComponentCodeEnum.serializer)
      ..add(BitesCreateEventMomentErrorComponent.serializer)
      ..add(BitesCreateEventMomentErrorComponentAttrEnum.serializer)
      ..add(BitesCreateEventMomentErrorComponentCodeEnum.serializer)
      ..add(BitesCreateHeadBiteCountErrorComponent.serializer)
      ..add(BitesCreateHeadBiteCountErrorComponentAttrEnum.serializer)
      ..add(BitesCreateHeadBiteCountErrorComponentCodeEnum.serializer)
      ..add(BitesCreateLeftArmBiteCountErrorComponent.serializer)
      ..add(BitesCreateLeftArmBiteCountErrorComponentAttrEnum.serializer)
      ..add(BitesCreateLeftArmBiteCountErrorComponentCodeEnum.serializer)
      ..add(BitesCreateLeftLegBiteCountErrorComponent.serializer)
      ..add(BitesCreateLeftLegBiteCountErrorComponentAttrEnum.serializer)
      ..add(BitesCreateLeftLegBiteCountErrorComponentCodeEnum.serializer)
      ..add(BitesCreateLocationNonFieldErrorsErrorComponent.serializer)
      ..add(BitesCreateLocationNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(BitesCreateLocationNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(BitesCreateLocationPointErrorComponent.serializer)
      ..add(BitesCreateLocationPointErrorComponentAttrEnum.serializer)
      ..add(BitesCreateLocationPointErrorComponentCodeEnum.serializer)
      ..add(BitesCreateLocationTypeErrorComponent.serializer)
      ..add(BitesCreateLocationTypeErrorComponentAttrEnum.serializer)
      ..add(BitesCreateLocationTypeErrorComponentCodeEnum.serializer)
      ..add(BitesCreateNonFieldErrorsErrorComponent.serializer)
      ..add(BitesCreateNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(BitesCreateNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(BitesCreateNoteErrorComponent.serializer)
      ..add(BitesCreateNoteErrorComponentAttrEnum.serializer)
      ..add(BitesCreateNoteErrorComponentCodeEnum.serializer)
      ..add(BitesCreateRightArmBiteCountErrorComponent.serializer)
      ..add(BitesCreateRightArmBiteCountErrorComponentAttrEnum.serializer)
      ..add(BitesCreateRightArmBiteCountErrorComponentCodeEnum.serializer)
      ..add(BitesCreateRightLegBiteCountErrorComponent.serializer)
      ..add(BitesCreateRightLegBiteCountErrorComponentAttrEnum.serializer)
      ..add(BitesCreateRightLegBiteCountErrorComponentCodeEnum.serializer)
      ..add(BitesCreateSentAtErrorComponent.serializer)
      ..add(BitesCreateSentAtErrorComponentAttrEnum.serializer)
      ..add(BitesCreateSentAtErrorComponentCodeEnum.serializer)
      ..add(BitesCreateTagsErrorComponent.serializer)
      ..add(BitesCreateTagsErrorComponentAttrEnum.serializer)
      ..add(BitesCreateTagsErrorComponentCodeEnum.serializer)
      ..add(BitesCreateTagsINDEXErrorComponent.serializer)
      ..add(BitesCreateTagsINDEXErrorComponentAttrEnum.serializer)
      ..add(BitesCreateTagsINDEXErrorComponentCodeEnum.serializer)
      ..add(BitesCreateValidationError.serializer)
      ..add(BitesCreateValidationErrorTypeEnum.serializer)
      ..add(BitesListCreatedAtErrorComponent.serializer)
      ..add(BitesListCreatedAtErrorComponentAttrEnum.serializer)
      ..add(BitesListCreatedAtErrorComponentCodeEnum.serializer)
      ..add(BitesListError.serializer)
      ..add(BitesListLocationCountryIdErrorComponent.serializer)
      ..add(BitesListLocationCountryIdErrorComponentAttrEnum.serializer)
      ..add(BitesListLocationCountryIdErrorComponentCodeEnum.serializer)
      ..add(BitesListLocationNuts2ErrorComponent.serializer)
      ..add(BitesListLocationNuts2ErrorComponentAttrEnum.serializer)
      ..add(BitesListLocationNuts2ErrorComponentCodeEnum.serializer)
      ..add(BitesListLocationNuts3ErrorComponent.serializer)
      ..add(BitesListLocationNuts3ErrorComponentAttrEnum.serializer)
      ..add(BitesListLocationNuts3ErrorComponentCodeEnum.serializer)
      ..add(BitesListMineCreatedAtErrorComponent.serializer)
      ..add(BitesListMineCreatedAtErrorComponentAttrEnum.serializer)
      ..add(BitesListMineCreatedAtErrorComponentCodeEnum.serializer)
      ..add(BitesListMineError.serializer)
      ..add(BitesListMineLocationCountryIdErrorComponent.serializer)
      ..add(BitesListMineLocationCountryIdErrorComponentAttrEnum.serializer)
      ..add(BitesListMineLocationCountryIdErrorComponentCodeEnum.serializer)
      ..add(BitesListMineLocationNuts2ErrorComponent.serializer)
      ..add(BitesListMineLocationNuts2ErrorComponentAttrEnum.serializer)
      ..add(BitesListMineLocationNuts2ErrorComponentCodeEnum.serializer)
      ..add(BitesListMineLocationNuts3ErrorComponent.serializer)
      ..add(BitesListMineLocationNuts3ErrorComponentAttrEnum.serializer)
      ..add(BitesListMineLocationNuts3ErrorComponentCodeEnum.serializer)
      ..add(BitesListMineOrderByErrorComponent.serializer)
      ..add(BitesListMineOrderByErrorComponentAttrEnum.serializer)
      ..add(BitesListMineOrderByErrorComponentCodeEnum.serializer)
      ..add(BitesListMineReceivedAtErrorComponent.serializer)
      ..add(BitesListMineReceivedAtErrorComponentAttrEnum.serializer)
      ..add(BitesListMineReceivedAtErrorComponentCodeEnum.serializer)
      ..add(BitesListMineShortIdErrorComponent.serializer)
      ..add(BitesListMineShortIdErrorComponentAttrEnum.serializer)
      ..add(BitesListMineShortIdErrorComponentCodeEnum.serializer)
      ..add(BitesListMineUpdatedAtErrorComponent.serializer)
      ..add(BitesListMineUpdatedAtErrorComponentAttrEnum.serializer)
      ..add(BitesListMineUpdatedAtErrorComponentCodeEnum.serializer)
      ..add(BitesListMineUserUuidErrorComponent.serializer)
      ..add(BitesListMineUserUuidErrorComponentAttrEnum.serializer)
      ..add(BitesListMineUserUuidErrorComponentCodeEnum.serializer)
      ..add(BitesListMineValidationError.serializer)
      ..add(BitesListMineValidationErrorTypeEnum.serializer)
      ..add(BitesListOrderByErrorComponent.serializer)
      ..add(BitesListOrderByErrorComponentAttrEnum.serializer)
      ..add(BitesListOrderByErrorComponentCodeEnum.serializer)
      ..add(BitesListReceivedAtErrorComponent.serializer)
      ..add(BitesListReceivedAtErrorComponentAttrEnum.serializer)
      ..add(BitesListReceivedAtErrorComponentCodeEnum.serializer)
      ..add(BitesListShortIdErrorComponent.serializer)
      ..add(BitesListShortIdErrorComponentAttrEnum.serializer)
      ..add(BitesListShortIdErrorComponentCodeEnum.serializer)
      ..add(BitesListUpdatedAtErrorComponent.serializer)
      ..add(BitesListUpdatedAtErrorComponentAttrEnum.serializer)
      ..add(BitesListUpdatedAtErrorComponentCodeEnum.serializer)
      ..add(BitesListUserUuidErrorComponent.serializer)
      ..add(BitesListUserUuidErrorComponentAttrEnum.serializer)
      ..add(BitesListUserUuidErrorComponentCodeEnum.serializer)
      ..add(BitesListValidationError.serializer)
      ..add(BitesListValidationErrorTypeEnum.serializer)
      ..add(BreedingSite.serializer)
      ..add(BreedingSiteSiteTypeEnum.serializer)
      ..add(BreedingsitesCreateCreatedAtErrorComponent.serializer)
      ..add(BreedingsitesCreateCreatedAtErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesCreateCreatedAtErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesCreateError.serializer)
      ..add(BreedingsitesCreateHasLarvaeErrorComponent.serializer)
      ..add(BreedingsitesCreateHasLarvaeErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesCreateHasLarvaeErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesCreateHasNearMosquitoesErrorComponent.serializer)
      ..add(
          BreedingsitesCreateHasNearMosquitoesErrorComponentAttrEnum.serializer)
      ..add(
          BreedingsitesCreateHasNearMosquitoesErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesCreateHasWaterErrorComponent.serializer)
      ..add(BreedingsitesCreateHasWaterErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesCreateHasWaterErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesCreateInPublicAreaErrorComponent.serializer)
      ..add(BreedingsitesCreateInPublicAreaErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesCreateInPublicAreaErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesCreateLocationNonFieldErrorsErrorComponent.serializer)
      ..add(BreedingsitesCreateLocationNonFieldErrorsErrorComponentAttrEnum
          .serializer)
      ..add(BreedingsitesCreateLocationNonFieldErrorsErrorComponentCodeEnum
          .serializer)
      ..add(BreedingsitesCreateLocationPointErrorComponent.serializer)
      ..add(BreedingsitesCreateLocationPointErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesCreateLocationPointErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesCreateLocationTypeErrorComponent.serializer)
      ..add(BreedingsitesCreateLocationTypeErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesCreateLocationTypeErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesCreateNonFieldErrorsErrorComponent.serializer)
      ..add(BreedingsitesCreateNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesCreateNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesCreateNoteErrorComponent.serializer)
      ..add(BreedingsitesCreateNoteErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesCreateNoteErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesCreatePhotosINDEXFileErrorComponent.serializer)
      ..add(BreedingsitesCreatePhotosINDEXFileErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesCreatePhotosINDEXFileErrorComponentCodeEnum.serializer)
      ..add(
          BreedingsitesCreatePhotosINDEXNonFieldErrorsErrorComponent.serializer)
      ..add(BreedingsitesCreatePhotosINDEXNonFieldErrorsErrorComponentAttrEnum
          .serializer)
      ..add(BreedingsitesCreatePhotosINDEXNonFieldErrorsErrorComponentCodeEnum
          .serializer)
      ..add(BreedingsitesCreatePhotosNonFieldErrorsErrorComponent.serializer)
      ..add(BreedingsitesCreatePhotosNonFieldErrorsErrorComponentAttrEnum
          .serializer)
      ..add(BreedingsitesCreatePhotosNonFieldErrorsErrorComponentCodeEnum
          .serializer)
      ..add(BreedingsitesCreateSentAtErrorComponent.serializer)
      ..add(BreedingsitesCreateSentAtErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesCreateSentAtErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesCreateSiteTypeErrorComponent.serializer)
      ..add(BreedingsitesCreateSiteTypeErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesCreateSiteTypeErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesCreateTagsErrorComponent.serializer)
      ..add(BreedingsitesCreateTagsErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesCreateTagsErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesCreateTagsINDEXErrorComponent.serializer)
      ..add(BreedingsitesCreateTagsINDEXErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesCreateTagsINDEXErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesCreateValidationError.serializer)
      ..add(BreedingsitesCreateValidationErrorTypeEnum.serializer)
      ..add(BreedingsitesListCreatedAtErrorComponent.serializer)
      ..add(BreedingsitesListCreatedAtErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListCreatedAtErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListError.serializer)
      ..add(BreedingsitesListLocationCountryIdErrorComponent.serializer)
      ..add(BreedingsitesListLocationCountryIdErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListLocationCountryIdErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListLocationNuts2ErrorComponent.serializer)
      ..add(BreedingsitesListLocationNuts2ErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListLocationNuts2ErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListLocationNuts3ErrorComponent.serializer)
      ..add(BreedingsitesListLocationNuts3ErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListLocationNuts3ErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListMineCreatedAtErrorComponent.serializer)
      ..add(BreedingsitesListMineCreatedAtErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListMineCreatedAtErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListMineError.serializer)
      ..add(BreedingsitesListMineLocationCountryIdErrorComponent.serializer)
      ..add(BreedingsitesListMineLocationCountryIdErrorComponentAttrEnum
          .serializer)
      ..add(BreedingsitesListMineLocationCountryIdErrorComponentCodeEnum
          .serializer)
      ..add(BreedingsitesListMineLocationNuts2ErrorComponent.serializer)
      ..add(BreedingsitesListMineLocationNuts2ErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListMineLocationNuts2ErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListMineLocationNuts3ErrorComponent.serializer)
      ..add(BreedingsitesListMineLocationNuts3ErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListMineLocationNuts3ErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListMineOrderByErrorComponent.serializer)
      ..add(BreedingsitesListMineOrderByErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListMineOrderByErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListMineReceivedAtErrorComponent.serializer)
      ..add(BreedingsitesListMineReceivedAtErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListMineReceivedAtErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListMineShortIdErrorComponent.serializer)
      ..add(BreedingsitesListMineShortIdErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListMineShortIdErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListMineUpdatedAtErrorComponent.serializer)
      ..add(BreedingsitesListMineUpdatedAtErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListMineUpdatedAtErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListMineUserUuidErrorComponent.serializer)
      ..add(BreedingsitesListMineUserUuidErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListMineUserUuidErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListMineValidationError.serializer)
      ..add(BreedingsitesListMineValidationErrorTypeEnum.serializer)
      ..add(BreedingsitesListOrderByErrorComponent.serializer)
      ..add(BreedingsitesListOrderByErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListOrderByErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListReceivedAtErrorComponent.serializer)
      ..add(BreedingsitesListReceivedAtErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListReceivedAtErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListShortIdErrorComponent.serializer)
      ..add(BreedingsitesListShortIdErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListShortIdErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListUpdatedAtErrorComponent.serializer)
      ..add(BreedingsitesListUpdatedAtErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListUpdatedAtErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListUserUuidErrorComponent.serializer)
      ..add(BreedingsitesListUserUuidErrorComponentAttrEnum.serializer)
      ..add(BreedingsitesListUserUuidErrorComponentCodeEnum.serializer)
      ..add(BreedingsitesListValidationError.serializer)
      ..add(BreedingsitesListValidationErrorTypeEnum.serializer)
      ..add(Campaign.serializer)
      ..add(CampaignsListCountryIdErrorComponent.serializer)
      ..add(CampaignsListCountryIdErrorComponentAttrEnum.serializer)
      ..add(CampaignsListCountryIdErrorComponentCodeEnum.serializer)
      ..add(CampaignsListError.serializer)
      ..add(CampaignsListOrderByErrorComponent.serializer)
      ..add(CampaignsListOrderByErrorComponentAttrEnum.serializer)
      ..add(CampaignsListOrderByErrorComponentCodeEnum.serializer)
      ..add(CampaignsListValidationError.serializer)
      ..add(CampaignsListValidationErrorTypeEnum.serializer)
      ..add(Country.serializer)
      ..add(CreateNotification.serializer)
      ..add(CreateNotificationMessage.serializer)
      ..add(CreateNotificationMessageRequest.serializer)
      ..add(Device.serializer)
      ..add(DeviceOs.serializer)
      ..add(DeviceOsRequest.serializer)
      ..add(DeviceRequest.serializer)
      ..add(DeviceRequestTypeEnum.serializer)
      ..add(DeviceTypeEnum.serializer)
      ..add(DeviceUpdate.serializer)
      ..add(DeviceUpdateRequest.serializer)
      ..add(DeviceUpdateTypeEnum.serializer)
      ..add(DevicesCreateDeviceIdErrorComponent.serializer)
      ..add(DevicesCreateDeviceIdErrorComponentAttrEnum.serializer)
      ..add(DevicesCreateDeviceIdErrorComponentCodeEnum.serializer)
      ..add(DevicesCreateError.serializer)
      ..add(DevicesCreateFcmTokenErrorComponent.serializer)
      ..add(DevicesCreateFcmTokenErrorComponentAttrEnum.serializer)
      ..add(DevicesCreateFcmTokenErrorComponentCodeEnum.serializer)
      ..add(DevicesCreateManufacturerErrorComponent.serializer)
      ..add(DevicesCreateManufacturerErrorComponentAttrEnum.serializer)
      ..add(DevicesCreateManufacturerErrorComponentCodeEnum.serializer)
      ..add(DevicesCreateMobileAppNonFieldErrorsErrorComponent.serializer)
      ..add(
          DevicesCreateMobileAppNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(
          DevicesCreateMobileAppNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(DevicesCreateMobileAppPackageNameErrorComponent.serializer)
      ..add(DevicesCreateMobileAppPackageNameErrorComponentAttrEnum.serializer)
      ..add(DevicesCreateMobileAppPackageNameErrorComponentCodeEnum.serializer)
      ..add(DevicesCreateMobileAppPackageVersionErrorComponent.serializer)
      ..add(
          DevicesCreateMobileAppPackageVersionErrorComponentAttrEnum.serializer)
      ..add(
          DevicesCreateMobileAppPackageVersionErrorComponentCodeEnum.serializer)
      ..add(DevicesCreateModelErrorComponent.serializer)
      ..add(DevicesCreateModelErrorComponentAttrEnum.serializer)
      ..add(DevicesCreateModelErrorComponentCodeEnum.serializer)
      ..add(DevicesCreateNameErrorComponent.serializer)
      ..add(DevicesCreateNameErrorComponentAttrEnum.serializer)
      ..add(DevicesCreateNameErrorComponentCodeEnum.serializer)
      ..add(DevicesCreateNonFieldErrorsErrorComponent.serializer)
      ..add(DevicesCreateNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(DevicesCreateNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(DevicesCreateOsLocaleErrorComponent.serializer)
      ..add(DevicesCreateOsLocaleErrorComponentAttrEnum.serializer)
      ..add(DevicesCreateOsLocaleErrorComponentCodeEnum.serializer)
      ..add(DevicesCreateOsNameErrorComponent.serializer)
      ..add(DevicesCreateOsNameErrorComponentAttrEnum.serializer)
      ..add(DevicesCreateOsNameErrorComponentCodeEnum.serializer)
      ..add(DevicesCreateOsNonFieldErrorsErrorComponent.serializer)
      ..add(DevicesCreateOsNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(DevicesCreateOsNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(DevicesCreateOsVersionErrorComponent.serializer)
      ..add(DevicesCreateOsVersionErrorComponentAttrEnum.serializer)
      ..add(DevicesCreateOsVersionErrorComponentCodeEnum.serializer)
      ..add(DevicesCreateTypeErrorComponent.serializer)
      ..add(DevicesCreateTypeErrorComponentAttrEnum.serializer)
      ..add(DevicesCreateTypeErrorComponentCodeEnum.serializer)
      ..add(DevicesCreateValidationError.serializer)
      ..add(DevicesCreateValidationErrorTypeEnum.serializer)
      ..add(DevicesPartialUpdateError.serializer)
      ..add(DevicesPartialUpdateFcmTokenErrorComponent.serializer)
      ..add(DevicesPartialUpdateFcmTokenErrorComponentAttrEnum.serializer)
      ..add(DevicesPartialUpdateFcmTokenErrorComponentCodeEnum.serializer)
      ..add(
          DevicesPartialUpdateMobileAppNonFieldErrorsErrorComponent.serializer)
      ..add(DevicesPartialUpdateMobileAppNonFieldErrorsErrorComponentAttrEnum
          .serializer)
      ..add(DevicesPartialUpdateMobileAppNonFieldErrorsErrorComponentCodeEnum
          .serializer)
      ..add(DevicesPartialUpdateMobileAppPackageNameErrorComponent.serializer)
      ..add(DevicesPartialUpdateMobileAppPackageNameErrorComponentAttrEnum
          .serializer)
      ..add(DevicesPartialUpdateMobileAppPackageNameErrorComponentCodeEnum
          .serializer)
      ..add(
          DevicesPartialUpdateMobileAppPackageVersionErrorComponent.serializer)
      ..add(DevicesPartialUpdateMobileAppPackageVersionErrorComponentAttrEnum
          .serializer)
      ..add(DevicesPartialUpdateMobileAppPackageVersionErrorComponentCodeEnum
          .serializer)
      ..add(DevicesPartialUpdateNameErrorComponent.serializer)
      ..add(DevicesPartialUpdateNameErrorComponentAttrEnum.serializer)
      ..add(DevicesPartialUpdateNameErrorComponentCodeEnum.serializer)
      ..add(DevicesPartialUpdateNonFieldErrorsErrorComponent.serializer)
      ..add(DevicesPartialUpdateNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(DevicesPartialUpdateNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(DevicesPartialUpdateOsLocaleErrorComponent.serializer)
      ..add(DevicesPartialUpdateOsLocaleErrorComponentAttrEnum.serializer)
      ..add(DevicesPartialUpdateOsLocaleErrorComponentCodeEnum.serializer)
      ..add(DevicesPartialUpdateOsNameErrorComponent.serializer)
      ..add(DevicesPartialUpdateOsNameErrorComponentAttrEnum.serializer)
      ..add(DevicesPartialUpdateOsNameErrorComponentCodeEnum.serializer)
      ..add(DevicesPartialUpdateOsNonFieldErrorsErrorComponent.serializer)
      ..add(
          DevicesPartialUpdateOsNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(
          DevicesPartialUpdateOsNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(DevicesPartialUpdateOsVersionErrorComponent.serializer)
      ..add(DevicesPartialUpdateOsVersionErrorComponentAttrEnum.serializer)
      ..add(DevicesPartialUpdateOsVersionErrorComponentCodeEnum.serializer)
      ..add(DevicesPartialUpdateValidationError.serializer)
      ..add(DevicesPartialUpdateValidationErrorTypeEnum.serializer)
      ..add(DevicesUpdateError.serializer)
      ..add(DevicesUpdateFcmTokenErrorComponent.serializer)
      ..add(DevicesUpdateFcmTokenErrorComponentAttrEnum.serializer)
      ..add(DevicesUpdateFcmTokenErrorComponentCodeEnum.serializer)
      ..add(DevicesUpdateMobileAppNonFieldErrorsErrorComponent.serializer)
      ..add(
          DevicesUpdateMobileAppNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(
          DevicesUpdateMobileAppNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(DevicesUpdateMobileAppPackageNameErrorComponent.serializer)
      ..add(DevicesUpdateMobileAppPackageNameErrorComponentAttrEnum.serializer)
      ..add(DevicesUpdateMobileAppPackageNameErrorComponentCodeEnum.serializer)
      ..add(DevicesUpdateMobileAppPackageVersionErrorComponent.serializer)
      ..add(
          DevicesUpdateMobileAppPackageVersionErrorComponentAttrEnum.serializer)
      ..add(
          DevicesUpdateMobileAppPackageVersionErrorComponentCodeEnum.serializer)
      ..add(DevicesUpdateNameErrorComponent.serializer)
      ..add(DevicesUpdateNameErrorComponentAttrEnum.serializer)
      ..add(DevicesUpdateNameErrorComponentCodeEnum.serializer)
      ..add(DevicesUpdateNonFieldErrorsErrorComponent.serializer)
      ..add(DevicesUpdateNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(DevicesUpdateNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(DevicesUpdateOsLocaleErrorComponent.serializer)
      ..add(DevicesUpdateOsLocaleErrorComponentAttrEnum.serializer)
      ..add(DevicesUpdateOsLocaleErrorComponentCodeEnum.serializer)
      ..add(DevicesUpdateOsNameErrorComponent.serializer)
      ..add(DevicesUpdateOsNameErrorComponentAttrEnum.serializer)
      ..add(DevicesUpdateOsNameErrorComponentCodeEnum.serializer)
      ..add(DevicesUpdateOsNonFieldErrorsErrorComponent.serializer)
      ..add(DevicesUpdateOsNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(DevicesUpdateOsNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(DevicesUpdateOsVersionErrorComponent.serializer)
      ..add(DevicesUpdateOsVersionErrorComponentAttrEnum.serializer)
      ..add(DevicesUpdateOsVersionErrorComponentCodeEnum.serializer)
      ..add(DevicesUpdateValidationError.serializer)
      ..add(DevicesUpdateValidationErrorTypeEnum.serializer)
      ..add(Error401.serializer)
      ..add(Error401CodeEnum.serializer)
      ..add(Error403.serializer)
      ..add(Error403CodeEnum.serializer)
      ..add(Error404.serializer)
      ..add(Error404CodeEnum.serializer)
      ..add(ErrorResponse401.serializer)
      ..add(ErrorResponse401TypeEnum.serializer)
      ..add(ErrorResponse403.serializer)
      ..add(ErrorResponse403TypeEnum.serializer)
      ..add(ErrorResponse404.serializer)
      ..add(ErrorResponse404TypeEnum.serializer)
      ..add(Fix.serializer)
      ..add(FixLocation.serializer)
      ..add(FixLocationRequest.serializer)
      ..add(FixRequest.serializer)
      ..add(FixesCreateCoverageUuidErrorComponent.serializer)
      ..add(FixesCreateCoverageUuidErrorComponentAttrEnum.serializer)
      ..add(FixesCreateCoverageUuidErrorComponentCodeEnum.serializer)
      ..add(FixesCreateCreatedAtErrorComponent.serializer)
      ..add(FixesCreateCreatedAtErrorComponentAttrEnum.serializer)
      ..add(FixesCreateCreatedAtErrorComponentCodeEnum.serializer)
      ..add(FixesCreateError.serializer)
      ..add(FixesCreateNonFieldErrorsErrorComponent.serializer)
      ..add(FixesCreateNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(FixesCreateNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(FixesCreatePointLatitudeErrorComponent.serializer)
      ..add(FixesCreatePointLatitudeErrorComponentAttrEnum.serializer)
      ..add(FixesCreatePointLatitudeErrorComponentCodeEnum.serializer)
      ..add(FixesCreatePointLongitudeErrorComponent.serializer)
      ..add(FixesCreatePointLongitudeErrorComponentAttrEnum.serializer)
      ..add(FixesCreatePointLongitudeErrorComponentCodeEnum.serializer)
      ..add(FixesCreatePointNonFieldErrorsErrorComponent.serializer)
      ..add(FixesCreatePointNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(FixesCreatePointNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(FixesCreatePowerErrorComponent.serializer)
      ..add(FixesCreatePowerErrorComponentAttrEnum.serializer)
      ..add(FixesCreatePowerErrorComponentCodeEnum.serializer)
      ..add(FixesCreateSentAtErrorComponent.serializer)
      ..add(FixesCreateSentAtErrorComponentAttrEnum.serializer)
      ..add(FixesCreateSentAtErrorComponentCodeEnum.serializer)
      ..add(FixesCreateValidationError.serializer)
      ..add(FixesCreateValidationErrorTypeEnum.serializer)
      ..add(GuestRegistration.serializer)
      ..add(GuestRegistrationRequest.serializer)
      ..add(LocalizedField.serializer)
      ..add(LocalizedFieldRequest.serializer)
      ..add(Location.serializer)
      ..add(LocationPoint.serializer)
      ..add(LocationRequest.serializer)
      ..add(LocationRequestTypeEnum.serializer)
      ..add(LocationTimezoneEnum.serializer)
      ..add(LocationTypeEnum.serializer)
      ..add(MetaNotificationRequest.serializer)
      ..add(MobileApp.serializer)
      ..add(MobileAppRequest.serializer)
      ..add(Notification.serializer)
      ..add(NotificationMessage.serializer)
      ..add(NotificationRequest.serializer)
      ..add(NotificationsCreateError.serializer)
      ..add(NotificationsCreateMessageBodyBgErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyBgErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyBgErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyBnErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyBnErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyBnErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyCaErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyCaErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyCaErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyDeErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyDeErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyDeErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyElErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyElErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyElErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyEnErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyEnErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyEnErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyEsErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyEsErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyEsErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyEuErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyEuErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyEuErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyFrErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyFrErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyFrErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyGlErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyGlErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyGlErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyHrErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyHrErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyHrErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyHuErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyHuErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyHuErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyItErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyItErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyItErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyLbErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyLbErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyLbErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyMkErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyMkErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyMkErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyNlErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyNlErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyNlErrorComponentCodeEnum.serializer)
      ..add(
          NotificationsCreateMessageBodyNonFieldErrorsErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyNonFieldErrorsErrorComponentAttrEnum
          .serializer)
      ..add(NotificationsCreateMessageBodyNonFieldErrorsErrorComponentCodeEnum
          .serializer)
      ..add(NotificationsCreateMessageBodyPtErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyPtErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyPtErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyRoErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyRoErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyRoErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodySlErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodySlErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodySlErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodySqErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodySqErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodySqErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodySrErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodySrErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodySrErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodySvErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodySvErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodySvErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyTrErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyTrErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyTrErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageBodyZhCNErrorComponent.serializer)
      ..add(NotificationsCreateMessageBodyZhCNErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageBodyZhCNErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageNonFieldErrorsErrorComponent.serializer)
      ..add(NotificationsCreateMessageNonFieldErrorsErrorComponentAttrEnum
          .serializer)
      ..add(NotificationsCreateMessageNonFieldErrorsErrorComponentCodeEnum
          .serializer)
      ..add(NotificationsCreateMessageTitleBgErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleBgErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleBgErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleBnErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleBnErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleBnErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleCaErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleCaErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleCaErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleDeErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleDeErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleDeErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleElErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleElErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleElErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleEnErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleEnErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleEnErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleEsErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleEsErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleEsErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleEuErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleEuErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleEuErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleFrErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleFrErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleFrErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleGlErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleGlErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleGlErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleHrErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleHrErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleHrErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleHuErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleHuErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleHuErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleItErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleItErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleItErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleLbErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleLbErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleLbErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleMkErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleMkErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleMkErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleNlErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleNlErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleNlErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleNonFieldErrorsErrorComponent
          .serializer)
      ..add(NotificationsCreateMessageTitleNonFieldErrorsErrorComponentAttrEnum
          .serializer)
      ..add(NotificationsCreateMessageTitleNonFieldErrorsErrorComponentCodeEnum
          .serializer)
      ..add(NotificationsCreateMessageTitlePtErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitlePtErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitlePtErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleRoErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleRoErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleRoErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleSlErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleSlErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleSlErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleSqErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleSqErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleSqErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleSrErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleSrErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleSrErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleSvErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleSvErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleSvErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleTrErrorComponent.serializer)
      ..add(NotificationsCreateMessageTitleTrErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateMessageTitleTrErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateMessageTitleZhCNErrorComponent.serializer)
      ..add(
          NotificationsCreateMessageTitleZhCNErrorComponentAttrEnum.serializer)
      ..add(
          NotificationsCreateMessageTitleZhCNErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateNonFieldErrorsErrorComponent.serializer)
      ..add(NotificationsCreateNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateReceiverTypeErrorComponent.serializer)
      ..add(NotificationsCreateReceiverTypeErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateReceiverTypeErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateTopicCodesErrorComponent.serializer)
      ..add(NotificationsCreateTopicCodesErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateTopicCodesErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateTopicCodesINDEXErrorComponent.serializer)
      ..add(NotificationsCreateTopicCodesINDEXErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateTopicCodesINDEXErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateUserUuidsErrorComponent.serializer)
      ..add(NotificationsCreateUserUuidsErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateUserUuidsErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateUserUuidsINDEXErrorComponent.serializer)
      ..add(NotificationsCreateUserUuidsINDEXErrorComponentAttrEnum.serializer)
      ..add(NotificationsCreateUserUuidsINDEXErrorComponentCodeEnum.serializer)
      ..add(NotificationsCreateValidationError.serializer)
      ..add(NotificationsCreateValidationErrorTypeEnum.serializer)
      ..add(NotificationsListError.serializer)
      ..add(NotificationsListMineError.serializer)
      ..add(NotificationsListMineOrderByErrorComponent.serializer)
      ..add(NotificationsListMineOrderByErrorComponentAttrEnum.serializer)
      ..add(NotificationsListMineOrderByErrorComponentCodeEnum.serializer)
      ..add(NotificationsListMineValidationError.serializer)
      ..add(NotificationsListMineValidationErrorTypeEnum.serializer)
      ..add(NotificationsListOrderByErrorComponent.serializer)
      ..add(NotificationsListOrderByErrorComponentAttrEnum.serializer)
      ..add(NotificationsListOrderByErrorComponentCodeEnum.serializer)
      ..add(NotificationsListValidationError.serializer)
      ..add(NotificationsListValidationErrorTypeEnum.serializer)
      ..add(NotificationsPartialUpdateError.serializer)
      ..add(NotificationsPartialUpdateIsReadErrorComponent.serializer)
      ..add(NotificationsPartialUpdateIsReadErrorComponentAttrEnum.serializer)
      ..add(NotificationsPartialUpdateIsReadErrorComponentCodeEnum.serializer)
      ..add(NotificationsPartialUpdateNonFieldErrorsErrorComponent.serializer)
      ..add(NotificationsPartialUpdateNonFieldErrorsErrorComponentAttrEnum
          .serializer)
      ..add(NotificationsPartialUpdateNonFieldErrorsErrorComponentCodeEnum
          .serializer)
      ..add(NotificationsPartialUpdateValidationError.serializer)
      ..add(NotificationsPartialUpdateValidationErrorTypeEnum.serializer)
      ..add(NotificationsUpdateError.serializer)
      ..add(NotificationsUpdateIsReadErrorComponent.serializer)
      ..add(NotificationsUpdateIsReadErrorComponentAttrEnum.serializer)
      ..add(NotificationsUpdateIsReadErrorComponentCodeEnum.serializer)
      ..add(NotificationsUpdateNonFieldErrorsErrorComponent.serializer)
      ..add(NotificationsUpdateNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(NotificationsUpdateNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(NotificationsUpdateValidationError.serializer)
      ..add(NotificationsUpdateValidationErrorTypeEnum.serializer)
      ..add(Observation.serializer)
      ..add(ObservationEventEnvironmentEnum.serializer)
      ..add(ObservationEventMomentEnum.serializer)
      ..add(ObservationUserPerceivedMosquitoAbdomenEnum.serializer)
      ..add(ObservationUserPerceivedMosquitoLegsEnum.serializer)
      ..add(ObservationUserPerceivedMosquitoSpecieEnum.serializer)
      ..add(ObservationUserPerceivedMosquitoThoraxEnum.serializer)
      ..add(ObservationsCreateCreatedAtErrorComponent.serializer)
      ..add(ObservationsCreateCreatedAtErrorComponentAttrEnum.serializer)
      ..add(ObservationsCreateCreatedAtErrorComponentCodeEnum.serializer)
      ..add(ObservationsCreateError.serializer)
      ..add(ObservationsCreateEventEnvironmentErrorComponent.serializer)
      ..add(ObservationsCreateEventEnvironmentErrorComponentAttrEnum.serializer)
      ..add(ObservationsCreateEventEnvironmentErrorComponentCodeEnum.serializer)
      ..add(ObservationsCreateEventMomentErrorComponent.serializer)
      ..add(ObservationsCreateEventMomentErrorComponentAttrEnum.serializer)
      ..add(ObservationsCreateEventMomentErrorComponentCodeEnum.serializer)
      ..add(ObservationsCreateLocationNonFieldErrorsErrorComponent.serializer)
      ..add(ObservationsCreateLocationNonFieldErrorsErrorComponentAttrEnum
          .serializer)
      ..add(ObservationsCreateLocationNonFieldErrorsErrorComponentCodeEnum
          .serializer)
      ..add(ObservationsCreateLocationPointErrorComponent.serializer)
      ..add(ObservationsCreateLocationPointErrorComponentAttrEnum.serializer)
      ..add(ObservationsCreateLocationPointErrorComponentCodeEnum.serializer)
      ..add(ObservationsCreateLocationTypeErrorComponent.serializer)
      ..add(ObservationsCreateLocationTypeErrorComponentAttrEnum.serializer)
      ..add(ObservationsCreateLocationTypeErrorComponentCodeEnum.serializer)
      ..add(ObservationsCreateNonFieldErrorsErrorComponent.serializer)
      ..add(ObservationsCreateNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(ObservationsCreateNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(ObservationsCreateNoteErrorComponent.serializer)
      ..add(ObservationsCreateNoteErrorComponentAttrEnum.serializer)
      ..add(ObservationsCreateNoteErrorComponentCodeEnum.serializer)
      ..add(ObservationsCreatePhotosINDEXFileErrorComponent.serializer)
      ..add(ObservationsCreatePhotosINDEXFileErrorComponentAttrEnum.serializer)
      ..add(ObservationsCreatePhotosINDEXFileErrorComponentCodeEnum.serializer)
      ..add(
          ObservationsCreatePhotosINDEXNonFieldErrorsErrorComponent.serializer)
      ..add(ObservationsCreatePhotosINDEXNonFieldErrorsErrorComponentAttrEnum
          .serializer)
      ..add(ObservationsCreatePhotosINDEXNonFieldErrorsErrorComponentCodeEnum
          .serializer)
      ..add(ObservationsCreatePhotosNonFieldErrorsErrorComponent.serializer)
      ..add(ObservationsCreatePhotosNonFieldErrorsErrorComponentAttrEnum
          .serializer)
      ..add(ObservationsCreatePhotosNonFieldErrorsErrorComponentCodeEnum
          .serializer)
      ..add(ObservationsCreateSentAtErrorComponent.serializer)
      ..add(ObservationsCreateSentAtErrorComponentAttrEnum.serializer)
      ..add(ObservationsCreateSentAtErrorComponentCodeEnum.serializer)
      ..add(ObservationsCreateTagsErrorComponent.serializer)
      ..add(ObservationsCreateTagsErrorComponentAttrEnum.serializer)
      ..add(ObservationsCreateTagsErrorComponentCodeEnum.serializer)
      ..add(ObservationsCreateTagsINDEXErrorComponent.serializer)
      ..add(ObservationsCreateTagsINDEXErrorComponentAttrEnum.serializer)
      ..add(ObservationsCreateTagsINDEXErrorComponentCodeEnum.serializer)
      ..add(ObservationsCreateUserPerceivedMosquitoAbdomenErrorComponent
          .serializer)
      ..add(ObservationsCreateUserPerceivedMosquitoAbdomenErrorComponentAttrEnum
          .serializer)
      ..add(ObservationsCreateUserPerceivedMosquitoAbdomenErrorComponentCodeEnum
          .serializer)
      ..add(
          ObservationsCreateUserPerceivedMosquitoLegsErrorComponent.serializer)
      ..add(ObservationsCreateUserPerceivedMosquitoLegsErrorComponentAttrEnum
          .serializer)
      ..add(ObservationsCreateUserPerceivedMosquitoLegsErrorComponentCodeEnum
          .serializer)
      ..add(ObservationsCreateUserPerceivedMosquitoSpecieErrorComponent
          .serializer)
      ..add(ObservationsCreateUserPerceivedMosquitoSpecieErrorComponentAttrEnum
          .serializer)
      ..add(ObservationsCreateUserPerceivedMosquitoSpecieErrorComponentCodeEnum
          .serializer)
      ..add(ObservationsCreateUserPerceivedMosquitoThoraxErrorComponent
          .serializer)
      ..add(ObservationsCreateUserPerceivedMosquitoThoraxErrorComponentAttrEnum
          .serializer)
      ..add(ObservationsCreateUserPerceivedMosquitoThoraxErrorComponentCodeEnum
          .serializer)
      ..add(ObservationsCreateValidationError.serializer)
      ..add(ObservationsCreateValidationErrorTypeEnum.serializer)
      ..add(ObservationsListCreatedAtErrorComponent.serializer)
      ..add(ObservationsListCreatedAtErrorComponentAttrEnum.serializer)
      ..add(ObservationsListCreatedAtErrorComponentCodeEnum.serializer)
      ..add(ObservationsListError.serializer)
      ..add(ObservationsListLocationCountryIdErrorComponent.serializer)
      ..add(ObservationsListLocationCountryIdErrorComponentAttrEnum.serializer)
      ..add(ObservationsListLocationCountryIdErrorComponentCodeEnum.serializer)
      ..add(ObservationsListLocationNuts2ErrorComponent.serializer)
      ..add(ObservationsListLocationNuts2ErrorComponentAttrEnum.serializer)
      ..add(ObservationsListLocationNuts2ErrorComponentCodeEnum.serializer)
      ..add(ObservationsListLocationNuts3ErrorComponent.serializer)
      ..add(ObservationsListLocationNuts3ErrorComponentAttrEnum.serializer)
      ..add(ObservationsListLocationNuts3ErrorComponentCodeEnum.serializer)
      ..add(ObservationsListMineCreatedAtErrorComponent.serializer)
      ..add(ObservationsListMineCreatedAtErrorComponentAttrEnum.serializer)
      ..add(ObservationsListMineCreatedAtErrorComponentCodeEnum.serializer)
      ..add(ObservationsListMineError.serializer)
      ..add(ObservationsListMineLocationCountryIdErrorComponent.serializer)
      ..add(ObservationsListMineLocationCountryIdErrorComponentAttrEnum
          .serializer)
      ..add(ObservationsListMineLocationCountryIdErrorComponentCodeEnum
          .serializer)
      ..add(ObservationsListMineLocationNuts2ErrorComponent.serializer)
      ..add(ObservationsListMineLocationNuts2ErrorComponentAttrEnum.serializer)
      ..add(ObservationsListMineLocationNuts2ErrorComponentCodeEnum.serializer)
      ..add(ObservationsListMineLocationNuts3ErrorComponent.serializer)
      ..add(ObservationsListMineLocationNuts3ErrorComponentAttrEnum.serializer)
      ..add(ObservationsListMineLocationNuts3ErrorComponentCodeEnum.serializer)
      ..add(ObservationsListMineOrderByErrorComponent.serializer)
      ..add(ObservationsListMineOrderByErrorComponentAttrEnum.serializer)
      ..add(ObservationsListMineOrderByErrorComponentCodeEnum.serializer)
      ..add(ObservationsListMineReceivedAtErrorComponent.serializer)
      ..add(ObservationsListMineReceivedAtErrorComponentAttrEnum.serializer)
      ..add(ObservationsListMineReceivedAtErrorComponentCodeEnum.serializer)
      ..add(ObservationsListMineShortIdErrorComponent.serializer)
      ..add(ObservationsListMineShortIdErrorComponentAttrEnum.serializer)
      ..add(ObservationsListMineShortIdErrorComponentCodeEnum.serializer)
      ..add(ObservationsListMineUpdatedAtErrorComponent.serializer)
      ..add(ObservationsListMineUpdatedAtErrorComponentAttrEnum.serializer)
      ..add(ObservationsListMineUpdatedAtErrorComponentCodeEnum.serializer)
      ..add(ObservationsListMineUserUuidErrorComponent.serializer)
      ..add(ObservationsListMineUserUuidErrorComponentAttrEnum.serializer)
      ..add(ObservationsListMineUserUuidErrorComponentCodeEnum.serializer)
      ..add(ObservationsListMineValidationError.serializer)
      ..add(ObservationsListMineValidationErrorTypeEnum.serializer)
      ..add(ObservationsListOrderByErrorComponent.serializer)
      ..add(ObservationsListOrderByErrorComponentAttrEnum.serializer)
      ..add(ObservationsListOrderByErrorComponentCodeEnum.serializer)
      ..add(ObservationsListReceivedAtErrorComponent.serializer)
      ..add(ObservationsListReceivedAtErrorComponentAttrEnum.serializer)
      ..add(ObservationsListReceivedAtErrorComponentCodeEnum.serializer)
      ..add(ObservationsListShortIdErrorComponent.serializer)
      ..add(ObservationsListShortIdErrorComponentAttrEnum.serializer)
      ..add(ObservationsListShortIdErrorComponentCodeEnum.serializer)
      ..add(ObservationsListUpdatedAtErrorComponent.serializer)
      ..add(ObservationsListUpdatedAtErrorComponentAttrEnum.serializer)
      ..add(ObservationsListUpdatedAtErrorComponentCodeEnum.serializer)
      ..add(ObservationsListUserUuidErrorComponent.serializer)
      ..add(ObservationsListUserUuidErrorComponentAttrEnum.serializer)
      ..add(ObservationsListUserUuidErrorComponentCodeEnum.serializer)
      ..add(ObservationsListValidationError.serializer)
      ..add(ObservationsListValidationErrorTypeEnum.serializer)
      ..add(PaginatedBiteList.serializer)
      ..add(PaginatedBreedingSiteList.serializer)
      ..add(PaginatedCampaignList.serializer)
      ..add(PaginatedNotificationList.serializer)
      ..add(PaginatedObservationList.serializer)
      ..add(PaginatedPartnerList.serializer)
      ..add(Partner.serializer)
      ..add(PartnerPoint.serializer)
      ..add(PasswordChangeRequest.serializer)
      ..add(PatchedDeviceUpdateRequest.serializer)
      ..add(PatchedNotificationRequest.serializer)
      ..add(PatchedUserRequest.serializer)
      ..add(PatchedUserRequestLocaleEnum.serializer)
      ..add(Photo.serializer)
      ..add(SimplePhoto.serializer)
      ..add(SimplePhotoRequest.serializer)
      ..add(TokenRefresh.serializer)
      ..add(TokenRefreshRequest.serializer)
      ..add(TokenVerifyRequest.serializer)
      ..add(TopicNotificationCreateRequest.serializer)
      ..add(TopicNotificationCreateRequestReceiverTypeEnum.serializer)
      ..add(User.serializer)
      ..add(UserLocaleEnum.serializer)
      ..add(UserNotificationCreateRequest.serializer)
      ..add(UserNotificationCreateRequestReceiverTypeEnum.serializer)
      ..add(UserRequest.serializer)
      ..add(UserRequestLocaleEnum.serializer)
      ..add(UsersPartialUpdateError.serializer)
      ..add(UsersPartialUpdateLocaleErrorComponent.serializer)
      ..add(UsersPartialUpdateLocaleErrorComponentAttrEnum.serializer)
      ..add(UsersPartialUpdateLocaleErrorComponentCodeEnum.serializer)
      ..add(UsersPartialUpdateNonFieldErrorsErrorComponent.serializer)
      ..add(UsersPartialUpdateNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(UsersPartialUpdateNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(UsersPartialUpdateValidationError.serializer)
      ..add(UsersPartialUpdateValidationErrorTypeEnum.serializer)
      ..add(UsersUpdateError.serializer)
      ..add(UsersUpdateLocaleErrorComponent.serializer)
      ..add(UsersUpdateLocaleErrorComponentAttrEnum.serializer)
      ..add(UsersUpdateLocaleErrorComponentCodeEnum.serializer)
      ..add(UsersUpdateNonFieldErrorsErrorComponent.serializer)
      ..add(UsersUpdateNonFieldErrorsErrorComponentAttrEnum.serializer)
      ..add(UsersUpdateNonFieldErrorsErrorComponentCodeEnum.serializer)
      ..add(UsersUpdateValidationError.serializer)
      ..add(UsersUpdateValidationErrorTypeEnum.serializer)
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(AuthChangePasswordError)]),
          () => new ListBuilder<AuthChangePasswordError>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(AuthObtainTokenError)]),
          () => new ListBuilder<AuthObtainTokenError>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(AuthRefreshTokenError)]),
          () => new ListBuilder<AuthRefreshTokenError>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(AuthSignupGuestError)]),
          () => new ListBuilder<AuthSignupGuestError>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(AuthVerifyTokenError)]),
          () => new ListBuilder<AuthVerifyTokenError>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(Bite)]),
          () => new ListBuilder<Bite>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(BitesCreateError)]),
          () => new ListBuilder<BitesCreateError>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(BitesListError)]),
          () => new ListBuilder<BitesListError>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(BitesListMineError)]),
          () => new ListBuilder<BitesListMineError>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(BreedingSite)]),
          () => new ListBuilder<BreedingSite>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(BreedingsitesCreateError)]),
          () => new ListBuilder<BreedingsitesCreateError>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(BreedingsitesListError)]),
          () => new ListBuilder<BreedingsitesListError>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(BreedingsitesListMineError)]),
          () => new ListBuilder<BreedingsitesListMineError>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(Campaign)]),
          () => new ListBuilder<Campaign>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(CampaignsListError)]),
          () => new ListBuilder<CampaignsListError>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(DevicesCreateError)]),
          () => new ListBuilder<DevicesCreateError>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(DevicesPartialUpdateError)]),
          () => new ListBuilder<DevicesPartialUpdateError>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(DevicesUpdateError)]),
          () => new ListBuilder<DevicesUpdateError>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(Error401)]),
          () => new ListBuilder<Error401>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(Error403)]),
          () => new ListBuilder<Error403>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(Error404)]),
          () => new ListBuilder<Error404>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(FixesCreateError)]),
          () => new ListBuilder<FixesCreateError>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(Notification)]),
          () => new ListBuilder<Notification>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(NotificationsCreateError)]),
          () => new ListBuilder<NotificationsCreateError>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(NotificationsListError)]),
          () => new ListBuilder<NotificationsListError>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(NotificationsListMineError)]),
          () => new ListBuilder<NotificationsListMineError>())
      ..addBuilderFactory(
          const FullType(BuiltList,
              const [const FullType(NotificationsPartialUpdateError)]),
          () => new ListBuilder<NotificationsPartialUpdateError>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(NotificationsUpdateError)]),
          () => new ListBuilder<NotificationsUpdateError>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(Observation)]),
          () => new ListBuilder<Observation>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(ObservationsCreateError)]),
          () => new ListBuilder<ObservationsCreateError>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(ObservationsListError)]),
          () => new ListBuilder<ObservationsListError>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(ObservationsListMineError)]),
          () => new ListBuilder<ObservationsListMineError>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(Partner)]),
          () => new ListBuilder<Partner>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => new ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => new ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => new ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => new ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => new ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(SimplePhoto)]),
          () => new ListBuilder<SimplePhoto>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => new ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(SimplePhoto)]),
          () => new ListBuilder<SimplePhoto>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(UsersPartialUpdateError)]),
          () => new ListBuilder<UsersPartialUpdateError>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(UsersUpdateError)]),
          () => new ListBuilder<UsersUpdateError>()))
    .build();

// ignore_for_file: deprecated_member_use_from_same_package,type=lint
